version: "3.7"
services: 
  db:
    image: "mysql:5.7"
    environment: 
    MYSQL_ROOT_PASSWORD: root 
    MYSQL_USERNAME: root 
    MYSQL_PASSWORD: 12345678
  ports:
    - "3307:3306"
  
  rails_api:
    depends_on: 
      - "db"
      